# Generated by Django 6.0.5 on 2026-05-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ophix_tasks', '0002_taskexecutionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientscheduleaccess',
            name='can_delete',
            field=models.BooleanField(default=False, help_text='Client may delete this artifact.', verbose_name='can delete'),
        ),
        migrations.AlterField(
            model_name='clientscheduleaccess',
            name='can_share',
            field=models.BooleanField(default=False, help_text='Reserved: future client-driven sharing. Currently unused.', verbose_name='can share'),
        ),
        migrations.AlterField(
            model_name='clientscheduleaccess',
            name='can_update',
            field=models.BooleanField(default=False, help_text='Client may overwrite this artifact.', verbose_name='can update'),
        ),
        migrations.AlterField(
            model_name='clientscheduleaccess',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Client can read this artifact (can_read).', verbose_name='enabled'),
        ),
        migrations.AlterField(
            model_name='clientscheduleaccess',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='clientscheduleaccess',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='ends_at',
            field=models.DateTimeField(blank=True, help_text='Stop including in responses after this UTC datetime.', null=True, verbose_name='ends at'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='interval',
            field=models.CharField(blank=True, default='', help_text="Recurring: cron expression (e.g. '0 2 * * *'). Mutually exclusive with run_at.", max_length=100, verbose_name='interval'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='report_error',
            field=models.BooleanField(default=False, help_text='Capture stderr and store in the execution log.', verbose_name='report errors'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='report_output',
            field=models.BooleanField(default=False, help_text='Capture stdout and store in the execution log.', verbose_name='report output'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='run_at',
            field=models.DateTimeField(blank=True, help_text='One-off: exact UTC datetime to run. Mutually exclusive with interval.', null=True, verbose_name='run at'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='starts_at',
            field=models.DateTimeField(blank=True, help_text='Do not include in responses before this UTC datetime.', null=True, verbose_name='starts at'),
        ),
        migrations.AlterField(
            model_name='taskexecutionlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
