# Generated by Django 6.0.6 on 2026-06-06 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ophix_core', '0013_category_label_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('enabled', models.BooleanField(default=True, verbose_name='enabled')),
                ('paused', models.BooleanField(default=False, help_text='Pause all tasks in this schedule for all clients. Tasks remain visible in responses but are marked paused.', verbose_name='paused')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Internal identifier used by Tier 2 clients (e.g. 'cron', 'systemd', 'wts').", max_length=50, unique=True, verbose_name='name')),
                ('label', models.CharField(help_text="Human-readable name shown in admin (e.g. 'Cron (/etc/cron.d)').", max_length=100, verbose_name='label')),
                ('interval_help', models.TextField(blank=True, default='', help_text='Documentation shown to operators when setting the interval field.', verbose_name='interval help')),
                ('validator_class', models.CharField(blank=True, default='', help_text="Dotted Python path to the validator class (e.g. 'ophix_tasks.validators.CronValidator').", max_length=200, verbose_name='validator class')),
                ('enabled', models.BooleanField(default=True, help_text='Disabled schedulers cannot be selected on new tasks.', verbose_name='enabled')),
            ],
            options={
                'verbose_name': 'Scheduler',
                'verbose_name_plural': 'Schedulers',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('command', models.TextField(verbose_name='command')),
                ('description', models.TextField(blank=True, default='', help_text='Optional note written as a comment in the generated schedule file.', verbose_name='description')),
                ('run_at', models.DateTimeField(blank=True, help_text='One-off task: the exact date and time to execute. Leave blank for a recurring task.', null=True, verbose_name='run at')),
                ('interval', models.CharField(blank=True, default='', help_text='Recurring task: interval expression for the assigned scheduler. Leave blank for a one-off task.', max_length=100, verbose_name='interval')),
                ('starts_at', models.DateTimeField(blank=True, help_text='Do not include in responses before this date and time.', null=True, verbose_name='starts at')),
                ('ends_at', models.DateTimeField(blank=True, help_text='Stop including in responses after this date and time.', null=True, verbose_name='ends at')),
                ('enabled', models.BooleanField(default=True, verbose_name='enabled')),
                ('paused', models.BooleanField(default=False, help_text='Pause this task for all clients. The task remains in responses but is marked paused.', verbose_name='paused')),
                ('stdout_handling', models.CharField(choices=[('inherit', 'Default (scheduler handles output)'), ('report', 'Report to server'), ('null', 'Discard (/dev/null)'), ('file', 'Append to log file')], default='inherit', help_text='Where to send standard output.', max_length=10, verbose_name='stdout handling')),
                ('stderr_handling', models.CharField(choices=[('inherit', 'Default (scheduler handles errors)'), ('report', 'Report to server'), ('null', 'Discard (/dev/null)'), ('merge', 'Merge with stdout (2>&1)'), ('file', 'Append to log file')], default='inherit', help_text='Where to send standard error.', max_length=10, verbose_name='stderr handling')),
                ('log_file', models.CharField(blank=True, default='', help_text="Path to append output to when stdout or stderr handling is set to 'file'.", max_length=500, verbose_name='log file')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='ophix_tasks.schedule', verbose_name='schedule')),
                ('scheduler', models.ForeignKey(blank=True, help_text='Target scheduling system. Determines the expected interval format.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='ophix_tasks.scheduler', verbose_name='scheduler')),
            ],
            options={
                'verbose_name': 'Scheduled Task',
                'verbose_name_plural': 'Scheduled Tasks',
                'ordering': ('schedule__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='TaskExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_at', models.DateTimeField(auto_now_add=True, verbose_name='reported at')),
                ('stream', models.CharField(choices=[('stdout', 'stdout only'), ('stderr', 'stderr only'), ('both', 'stdout + stderr')], default='both', help_text='Which output stream(s) were captured.', max_length=6, verbose_name='stream')),
                ('output', models.TextField(blank=True, default='', verbose_name='output')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ophix_core.client', verbose_name='client')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='ophix_tasks.scheduledtask', verbose_name='task')),
            ],
            options={
                'verbose_name': 'Execution Log',
                'verbose_name_plural': 'Execution Logs',
                'ordering': ('-reported_at',),
            },
        ),
        migrations.CreateModel(
            name='ClientScheduleAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Client can read this artifact (can_read).', verbose_name='enabled')),
                ('can_update', models.BooleanField(default=False, help_text='Client may overwrite this artifact.', verbose_name='can update')),
                ('can_delete', models.BooleanField(default=False, help_text='Client may delete this artifact.', verbose_name='can delete')),
                ('can_share', models.BooleanField(default=False, help_text='Reserved: future client-driven sharing. Currently unused.', verbose_name='can share')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('paused', models.BooleanField(default=False, help_text='Pause all tasks in this schedule for this client only. Tasks remain visible in responses but are marked paused.', verbose_name='paused')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ophix_core.client', verbose_name='client')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_access', to='ophix_tasks.schedule', verbose_name='schedule')),
            ],
            options={
                'verbose_name': 'Client Schedule Access',
                'verbose_name_plural': 'Client Schedule Access',
                'unique_together': {('client', 'schedule')},
            },
        ),
    ]
