# Generated by Django 6.0.5 on 2026-05-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ophix_tasks', '0005_scheduler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtask',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Optional note written as a comment in the generated schedule file.', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='ends_at',
            field=models.DateTimeField(blank=True, help_text='Stop including in responses after this date and time.', null=True, verbose_name='ends at'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='interval',
            field=models.CharField(blank=True, default='', help_text='Recurring task: interval expression for the assigned scheduler. Leave blank for a one-off task.', max_length=100, verbose_name='interval'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='log_file',
            field=models.CharField(blank=True, default='', help_text="Path to append output to when stdout or stderr handling is set to 'file'.", max_length=500, verbose_name='log file'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='run_at',
            field=models.DateTimeField(blank=True, help_text='One-off task: the exact date and time to execute. Leave blank for a recurring task.', null=True, verbose_name='run at'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='starts_at',
            field=models.DateTimeField(blank=True, help_text='Do not include in responses before this date and time.', null=True, verbose_name='starts at'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='stderr_handling',
            field=models.CharField(choices=[('inherit', 'Default (scheduler handles errors)'), ('report', 'Report to server'), ('null', 'Discard (/dev/null)'), ('merge', 'Merge with stdout (2>&1)'), ('file', 'Append to log file')], default='inherit', help_text='Where to send standard error.', max_length=10, verbose_name='stderr handling'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='stdout_handling',
            field=models.CharField(choices=[('inherit', 'Default (scheduler handles output)'), ('report', 'Report to server'), ('null', 'Discard (/dev/null)'), ('file', 'Append to log file')], default='inherit', help_text='Where to send standard output.', max_length=10, verbose_name='stdout handling'),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
